// Hey Emacs, this is -*- coding: utf-8 mode: c++ -*-
#ifndef __RH_FOR_EACH_h__
#define __RH_FOR_EACH_h__

// This guard is required for MSVC compilers to do macro-expansion correctly.
// see http://stackoverflow.com/questions/5134523/msvc-doesnt-expand-va-args-correctly
#define RH__FE_EXPAND(x) x

// Make a FOREACH macro
#define RH__FE_1(a, x) a(x)
#define RH__FE_2(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_1(a, __VA_ARGS__))
#define RH__FE_3(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_2(a, __VA_ARGS__))
#define RH__FE_4(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_3(a, __VA_ARGS__))
#define RH__FE_5(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_4(a, __VA_ARGS__))
#define RH__FE_6(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_5(a, __VA_ARGS__))
#define RH__FE_7(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_6(a, __VA_ARGS__))
#define RH__FE_8(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_7(a, __VA_ARGS__))
#define RH__FE_9(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_8(a, __VA_ARGS__))
#define RH__FE_10(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_9(a, __VA_ARGS__))
#define RH__FE_11(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_10(a, __VA_ARGS__))
#define RH__FE_12(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_11(a, __VA_ARGS__))
#define RH__FE_13(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_12(a, __VA_ARGS__))
#define RH__FE_14(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_13(a, __VA_ARGS__))
#define RH__FE_15(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_14(a, __VA_ARGS__))
#define RH__FE_16(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_15(a, __VA_ARGS__))
#define RH__FE_17(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_16(a, __VA_ARGS__))
#define RH__FE_18(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_17(a, __VA_ARGS__))
#define RH__FE_19(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_18(a, __VA_ARGS__))
#define RH__FE_20(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_19(a, __VA_ARGS__))
#define RH__FE_21(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_20(a, __VA_ARGS__))
#define RH__FE_22(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_21(a, __VA_ARGS__))
#define RH__FE_23(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_22(a, __VA_ARGS__))
#define RH__FE_24(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_23(a, __VA_ARGS__))
#define RH__FE_25(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_24(a, __VA_ARGS__))
#define RH__FE_26(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_25(a, __VA_ARGS__))
#define RH__FE_27(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_26(a, __VA_ARGS__))
#define RH__FE_28(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_27(a, __VA_ARGS__))
#define RH__FE_29(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_28(a, __VA_ARGS__))
#define RH__FE_30(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_29(a, __VA_ARGS__))
#define RH__FE_31(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_30(a, __VA_ARGS__))
#define RH__FE_32(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_31(a, __VA_ARGS__))
#define RH__FE_33(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_32(a, __VA_ARGS__))
#define RH__FE_34(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_33(a, __VA_ARGS__))
#define RH__FE_35(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_34(a, __VA_ARGS__))
#define RH__FE_36(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_35(a, __VA_ARGS__))
#define RH__FE_37(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_36(a, __VA_ARGS__))
#define RH__FE_38(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_37(a, __VA_ARGS__))
#define RH__FE_39(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_38(a, __VA_ARGS__))
#define RH__FE_40(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_39(a, __VA_ARGS__))
#define RH__FE_41(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_40(a, __VA_ARGS__))
#define RH__FE_42(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_41(a, __VA_ARGS__))
#define RH__FE_43(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_42(a, __VA_ARGS__))
#define RH__FE_44(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_43(a, __VA_ARGS__))
#define RH__FE_45(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_44(a, __VA_ARGS__))
#define RH__FE_46(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_45(a, __VA_ARGS__))
#define RH__FE_47(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_46(a, __VA_ARGS__))
#define RH__FE_48(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_47(a, __VA_ARGS__))
#define RH__FE_49(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_48(a, __VA_ARGS__))
#define RH__FE_50(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_49(a, __VA_ARGS__))
#define RH__FE_51(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_50(a, __VA_ARGS__))
#define RH__FE_52(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_51(a, __VA_ARGS__))
#define RH__FE_53(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_52(a, __VA_ARGS__))
#define RH__FE_54(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_53(a, __VA_ARGS__))
#define RH__FE_55(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_54(a, __VA_ARGS__))
#define RH__FE_56(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_55(a, __VA_ARGS__))
#define RH__FE_57(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_56(a, __VA_ARGS__))
#define RH__FE_58(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_57(a, __VA_ARGS__))
#define RH__FE_59(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_58(a, __VA_ARGS__))
#define RH__FE_60(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_59(a, __VA_ARGS__))
#define RH__FE_61(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_60(a, __VA_ARGS__))
#define RH__FE_62(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_61(a, __VA_ARGS__))
#define RH__FE_63(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_62(a, __VA_ARGS__))
#define RH__FE_64(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_63(a, __VA_ARGS__))
#define RH__FE_65(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_64(a, __VA_ARGS__))
#define RH__FE_66(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_65(a, __VA_ARGS__))
#define RH__FE_67(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_66(a, __VA_ARGS__))
#define RH__FE_68(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_67(a, __VA_ARGS__))
#define RH__FE_69(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_68(a, __VA_ARGS__))
#define RH__FE_70(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_69(a, __VA_ARGS__))
#define RH__FE_71(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_70(a, __VA_ARGS__))
#define RH__FE_72(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_71(a, __VA_ARGS__))
#define RH__FE_73(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_72(a, __VA_ARGS__))
#define RH__FE_74(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_73(a, __VA_ARGS__))
#define RH__FE_75(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_74(a, __VA_ARGS__))
#define RH__FE_76(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_75(a, __VA_ARGS__))
#define RH__FE_77(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_76(a, __VA_ARGS__))
#define RH__FE_78(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_77(a, __VA_ARGS__))
#define RH__FE_79(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_78(a, __VA_ARGS__))
#define RH__FE_80(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_79(a, __VA_ARGS__))
#define RH__FE_81(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_80(a, __VA_ARGS__))
#define RH__FE_82(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_81(a, __VA_ARGS__))
#define RH__FE_83(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_82(a, __VA_ARGS__))
#define RH__FE_84(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_83(a, __VA_ARGS__))
#define RH__FE_85(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_84(a, __VA_ARGS__))
#define RH__FE_86(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_85(a, __VA_ARGS__))
#define RH__FE_87(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_86(a, __VA_ARGS__))
#define RH__FE_88(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_87(a, __VA_ARGS__))
#define RH__FE_89(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_88(a, __VA_ARGS__))
#define RH__FE_90(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_89(a, __VA_ARGS__))
#define RH__FE_91(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_90(a, __VA_ARGS__))
#define RH__FE_92(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_91(a, __VA_ARGS__))
#define RH__FE_93(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_92(a, __VA_ARGS__))
#define RH__FE_94(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_93(a, __VA_ARGS__))
#define RH__FE_95(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_94(a, __VA_ARGS__))
#define RH__FE_96(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_95(a, __VA_ARGS__))
#define RH__FE_97(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_96(a, __VA_ARGS__))
#define RH__FE_98(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_97(a, __VA_ARGS__))
#define RH__FE_99(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_98(a, __VA_ARGS__))
#define RH__FE_100(a, x, ...) RH__FE_EXPAND(a(x) RH__FE_99(a, __VA_ARGS__))

#define RH__FE_GET_MACRO(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,_65,_66,_67,_68,_69,_70,_71,_72,_73,_74,_75,_76,_77,_78,_79,_80,_81,_82,_83,_84,_85,_86,_87,_88,_89,_90,_91,_92,_93,_94,_95,_96,_97,_98,_99,_100,name,...) name

#define RH_FOR_EACH(a,...) \
RH__FE_EXPAND(RH__FE_GET_MACRO(__VA_ARGS__,RH__FE_100,RH__FE_99,RH__FE_98,RH__FE_97,RH__FE_96,RH__FE_95,RH__FE_94,RH__FE_93,RH__FE_92,RH__FE_91,RH__FE_90,RH__FE_89,RH__FE_88,RH__FE_87,RH__FE_86,RH__FE_85,RH__FE_84,RH__FE_83,RH__FE_82,RH__FE_81,RH__FE_80,RH__FE_79,RH__FE_78,RH__FE_77,RH__FE_76,RH__FE_75,RH__FE_74,RH__FE_73,RH__FE_72,RH__FE_71,RH__FE_70,RH__FE_69,RH__FE_68,RH__FE_67,RH__FE_66,RH__FE_65,RH__FE_64,RH__FE_63,RH__FE_62,RH__FE_61,RH__FE_60,RH__FE_59,RH__FE_58,RH__FE_57,RH__FE_56,RH__FE_55,RH__FE_54,RH__FE_53,RH__FE_52,RH__FE_51,RH__FE_50,RH__FE_49,RH__FE_48,RH__FE_47,RH__FE_46,RH__FE_45,RH__FE_44,RH__FE_43,RH__FE_42,RH__FE_41,RH__FE_40,RH__FE_39,RH__FE_38,RH__FE_37,RH__FE_36,RH__FE_35,RH__FE_34,RH__FE_33,RH__FE_32,RH__FE_31,RH__FE_30,RH__FE_29,RH__FE_28,RH__FE_27,RH__FE_26,RH__FE_25,RH__FE_24,RH__FE_23,RH__FE_22,RH__FE_21,RH__FE_20,RH__FE_19,RH__FE_18,RH__FE_17,RH__FE_16,RH__FE_15,RH__FE_14,RH__FE_13,RH__FE_12,RH__FE_11,RH__FE_10,RH__FE_9,RH__FE_8,RH__FE_7,RH__FE_6,RH__FE_5,RH__FE_4,RH__FE_3,RH__FE_2,RH__FE_1,)(a,__VA_ARGS__))

#endif //__RH_FOR_EACH_h__
