// Hey Emacs, this is -*- coding: utf-8 mode: c++ -*-
#ifndef __RH_FOR_EACH_h__
#define __RH_FOR_EACH_h__

// This guard is required for MSVC compilers to do macro-expansion correctly.
// see http://stackoverflow.com/questions/5134523/msvc-doesnt-expand-va-args-correctly
#define RH__EXPAND(x) x

// Make a FOREACH macro
#define RH__FE_1(action, x) action(x)
#define RH__FE_2(action, x, ...) RH__EXPAND(action(x) RH__FE_1(action, __VA_ARGS__))
#define RH__FE_3(action, x, ...) RH__EXPAND(action(x) RH__FE_2(action, __VA_ARGS__))
#define RH__FE_4(action, x, ...) RH__EXPAND(action(x) RH__FE_3(action, __VA_ARGS__))
#define RH__FE_5(action, x, ...) RH__EXPAND(action(x) RH__FE_4(action, __VA_ARGS__))
#define RH__FE_6(action, x, ...) RH__EXPAND(action(x) RH__FE_5(action, __VA_ARGS__))
#define RH__FE_7(action, x, ...) RH__EXPAND(action(x) RH__FE_6(action, __VA_ARGS__))
#define RH__FE_8(action, x, ...) RH__EXPAND(action(x) RH__FE_7(action, __VA_ARGS__))
#define RH__FE_9(action, x, ...) RH__EXPAND(action(x) RH__FE_8(action, __VA_ARGS__))
#define RH__FE_10(action, x, ...) RH__EXPAND(action(x) RH__FE_9(action, __VA_ARGS__))
#define RH__FE_11(action, x, ...) RH__EXPAND(action(x) RH__FE_10(action, __VA_ARGS__))
#define RH__FE_12(action, x, ...) RH__EXPAND(action(x) RH__FE_11(action, __VA_ARGS__))
#define RH__FE_13(action, x, ...) RH__EXPAND(action(x) RH__FE_12(action, __VA_ARGS__))
#define RH__FE_14(action, x, ...) RH__EXPAND(action(x) RH__FE_13(action, __VA_ARGS__))
#define RH__FE_15(action, x, ...) RH__EXPAND(action(x) RH__FE_14(action, __VA_ARGS__))
#define RH__FE_16(action, x, ...) RH__EXPAND(action(x) RH__FE_15(action, __VA_ARGS__))
#define RH__FE_17(action, x, ...) RH__EXPAND(action(x) RH__FE_16(action, __VA_ARGS__))
#define RH__FE_18(action, x, ...) RH__EXPAND(action(x) RH__FE_17(action, __VA_ARGS__))
#define RH__FE_19(action, x, ...) RH__EXPAND(action(x) RH__FE_18(action, __VA_ARGS__))
#define RH__FE_20(action, x, ...) RH__EXPAND(action(x) RH__FE_19(action, __VA_ARGS__))
#define RH__FE_21(action, x, ...) RH__EXPAND(action(x) RH__FE_20(action, __VA_ARGS__))
#define RH__FE_22(action, x, ...) RH__EXPAND(action(x) RH__FE_21(action, __VA_ARGS__))
#define RH__FE_23(action, x, ...) RH__EXPAND(action(x) RH__FE_22(action, __VA_ARGS__))
#define RH__FE_24(action, x, ...) RH__EXPAND(action(x) RH__FE_23(action, __VA_ARGS__))
#define RH__FE_25(action, x, ...) RH__EXPAND(action(x) RH__FE_24(action, __VA_ARGS__))
#define RH__FE_26(action, x, ...) RH__EXPAND(action(x) RH__FE_25(action, __VA_ARGS__))
#define RH__FE_27(action, x, ...) RH__EXPAND(action(x) RH__FE_26(action, __VA_ARGS__))
#define RH__FE_28(action, x, ...) RH__EXPAND(action(x) RH__FE_27(action, __VA_ARGS__))
#define RH__FE_29(action, x, ...) RH__EXPAND(action(x) RH__FE_28(action, __VA_ARGS__))
#define RH__FE_30(action, x, ...) RH__EXPAND(action(x) RH__FE_29(action, __VA_ARGS__))
#define RH__FE_31(action, x, ...) RH__EXPAND(action(x) RH__FE_30(action, __VA_ARGS__))
#define RH__FE_32(action, x, ...) RH__EXPAND(action(x) RH__FE_31(action, __VA_ARGS__))
#define RH__FE_33(action, x, ...) RH__EXPAND(action(x) RH__FE_32(action, __VA_ARGS__))
#define RH__FE_34(action, x, ...) RH__EXPAND(action(x) RH__FE_33(action, __VA_ARGS__))
#define RH__FE_35(action, x, ...) RH__EXPAND(action(x) RH__FE_34(action, __VA_ARGS__))
#define RH__FE_36(action, x, ...) RH__EXPAND(action(x) RH__FE_35(action, __VA_ARGS__))
#define RH__FE_37(action, x, ...) RH__EXPAND(action(x) RH__FE_36(action, __VA_ARGS__))
#define RH__FE_38(action, x, ...) RH__EXPAND(action(x) RH__FE_37(action, __VA_ARGS__))
#define RH__FE_39(action, x, ...) RH__EXPAND(action(x) RH__FE_38(action, __VA_ARGS__))
#define RH__FE_40(action, x, ...) RH__EXPAND(action(x) RH__FE_39(action, __VA_ARGS__))
#define RH__FE_41(action, x, ...) RH__EXPAND(action(x) RH__FE_40(action, __VA_ARGS__))
#define RH__FE_42(action, x, ...) RH__EXPAND(action(x) RH__FE_41(action, __VA_ARGS__))
#define RH__FE_43(action, x, ...) RH__EXPAND(action(x) RH__FE_42(action, __VA_ARGS__))
#define RH__FE_44(action, x, ...) RH__EXPAND(action(x) RH__FE_43(action, __VA_ARGS__))
#define RH__FE_45(action, x, ...) RH__EXPAND(action(x) RH__FE_44(action, __VA_ARGS__))
#define RH__FE_46(action, x, ...) RH__EXPAND(action(x) RH__FE_45(action, __VA_ARGS__))
#define RH__FE_47(action, x, ...) RH__EXPAND(action(x) RH__FE_46(action, __VA_ARGS__))
#define RH__FE_48(action, x, ...) RH__EXPAND(action(x) RH__FE_47(action, __VA_ARGS__))
#define RH__FE_49(action, x, ...) RH__EXPAND(action(x) RH__FE_48(action, __VA_ARGS__))
#define RH__FE_50(action, x, ...) RH__EXPAND(action(x) RH__FE_49(action, __VA_ARGS__))
#define RH__FE_51(action, x, ...) RH__EXPAND(action(x) RH__FE_50(action, __VA_ARGS__))
#define RH__FE_52(action, x, ...) RH__EXPAND(action(x) RH__FE_51(action, __VA_ARGS__))
#define RH__FE_53(action, x, ...) RH__EXPAND(action(x) RH__FE_52(action, __VA_ARGS__))
#define RH__FE_54(action, x, ...) RH__EXPAND(action(x) RH__FE_53(action, __VA_ARGS__))
#define RH__FE_55(action, x, ...) RH__EXPAND(action(x) RH__FE_54(action, __VA_ARGS__))
#define RH__FE_56(action, x, ...) RH__EXPAND(action(x) RH__FE_55(action, __VA_ARGS__))
#define RH__FE_57(action, x, ...) RH__EXPAND(action(x) RH__FE_56(action, __VA_ARGS__))
#define RH__FE_58(action, x, ...) RH__EXPAND(action(x) RH__FE_57(action, __VA_ARGS__))
#define RH__FE_59(action, x, ...) RH__EXPAND(action(x) RH__FE_58(action, __VA_ARGS__))
#define RH__FE_60(action, x, ...) RH__EXPAND(action(x) RH__FE_59(action, __VA_ARGS__))
#define RH__FE_61(action, x, ...) RH__EXPAND(action(x) RH__FE_60(action, __VA_ARGS__))
#define RH__FE_62(action, x, ...) RH__EXPAND(action(x) RH__FE_61(action, __VA_ARGS__))
#define RH__FE_63(action, x, ...) RH__EXPAND(action(x) RH__FE_62(action, __VA_ARGS__))
#define RH__FE_64(action, x, ...) RH__EXPAND(action(x) RH__FE_63(action, __VA_ARGS__))
#define RH__FE_65(action, x, ...) RH__EXPAND(action(x) RH__FE_64(action, __VA_ARGS__))
#define RH__FE_66(action, x, ...) RH__EXPAND(action(x) RH__FE_65(action, __VA_ARGS__))
#define RH__FE_67(action, x, ...) RH__EXPAND(action(x) RH__FE_66(action, __VA_ARGS__))
#define RH__FE_68(action, x, ...) RH__EXPAND(action(x) RH__FE_67(action, __VA_ARGS__))
#define RH__FE_69(action, x, ...) RH__EXPAND(action(x) RH__FE_68(action, __VA_ARGS__))
#define RH__FE_70(action, x, ...) RH__EXPAND(action(x) RH__FE_69(action, __VA_ARGS__))
#define RH__FE_71(action, x, ...) RH__EXPAND(action(x) RH__FE_70(action, __VA_ARGS__))
#define RH__FE_72(action, x, ...) RH__EXPAND(action(x) RH__FE_71(action, __VA_ARGS__))
#define RH__FE_73(action, x, ...) RH__EXPAND(action(x) RH__FE_72(action, __VA_ARGS__))
#define RH__FE_74(action, x, ...) RH__EXPAND(action(x) RH__FE_73(action, __VA_ARGS__))
#define RH__FE_75(action, x, ...) RH__EXPAND(action(x) RH__FE_74(action, __VA_ARGS__))
#define RH__FE_76(action, x, ...) RH__EXPAND(action(x) RH__FE_75(action, __VA_ARGS__))
#define RH__FE_77(action, x, ...) RH__EXPAND(action(x) RH__FE_76(action, __VA_ARGS__))
#define RH__FE_78(action, x, ...) RH__EXPAND(action(x) RH__FE_77(action, __VA_ARGS__))
#define RH__FE_79(action, x, ...) RH__EXPAND(action(x) RH__FE_78(action, __VA_ARGS__))
#define RH__FE_80(action, x, ...) RH__EXPAND(action(x) RH__FE_79(action, __VA_ARGS__))
#define RH__FE_81(action, x, ...) RH__EXPAND(action(x) RH__FE_80(action, __VA_ARGS__))
#define RH__FE_82(action, x, ...) RH__EXPAND(action(x) RH__FE_81(action, __VA_ARGS__))
#define RH__FE_83(action, x, ...) RH__EXPAND(action(x) RH__FE_82(action, __VA_ARGS__))
#define RH__FE_84(action, x, ...) RH__EXPAND(action(x) RH__FE_83(action, __VA_ARGS__))
#define RH__FE_85(action, x, ...) RH__EXPAND(action(x) RH__FE_84(action, __VA_ARGS__))
#define RH__FE_86(action, x, ...) RH__EXPAND(action(x) RH__FE_85(action, __VA_ARGS__))
#define RH__FE_87(action, x, ...) RH__EXPAND(action(x) RH__FE_86(action, __VA_ARGS__))
#define RH__FE_88(action, x, ...) RH__EXPAND(action(x) RH__FE_87(action, __VA_ARGS__))
#define RH__FE_89(action, x, ...) RH__EXPAND(action(x) RH__FE_88(action, __VA_ARGS__))
#define RH__FE_90(action, x, ...) RH__EXPAND(action(x) RH__FE_89(action, __VA_ARGS__))
#define RH__FE_91(action, x, ...) RH__EXPAND(action(x) RH__FE_90(action, __VA_ARGS__))
#define RH__FE_92(action, x, ...) RH__EXPAND(action(x) RH__FE_91(action, __VA_ARGS__))
#define RH__FE_93(action, x, ...) RH__EXPAND(action(x) RH__FE_92(action, __VA_ARGS__))
#define RH__FE_94(action, x, ...) RH__EXPAND(action(x) RH__FE_93(action, __VA_ARGS__))
#define RH__FE_95(action, x, ...) RH__EXPAND(action(x) RH__FE_94(action, __VA_ARGS__))
#define RH__FE_96(action, x, ...) RH__EXPAND(action(x) RH__FE_95(action, __VA_ARGS__))
#define RH__FE_97(action, x, ...) RH__EXPAND(action(x) RH__FE_96(action, __VA_ARGS__))
#define RH__FE_98(action, x, ...) RH__EXPAND(action(x) RH__FE_97(action, __VA_ARGS__))
#define RH__FE_99(action, x, ...) RH__EXPAND(action(x) RH__FE_98(action, __VA_ARGS__))
#define RH__FE_100(action, x, ...) RH__EXPAND(action(x) RH__FE_99(action, __VA_ARGS__))

#define RH__GET_MACRO(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,_65,_66,_67,_68,_69,_70,_71,_72,_73,_74,_75,_76,_77,_78,_79,_80,_81,_82,_83,_84,_85,_86,_87,_88,_89,_90,_91,_92,_93,_94,_95,_96,_97,_98,_99,_100,name,...) name

#define RH_FOR_EACH(action,...) \
RH__EXPAND(RH__GET_MACRO(__VA_ARGS__,RH__FE_100,RH__FE_99,RH__FE_98,RH__FE_97,RH__FE_96,RH__FE_95,RH__FE_94,RH__FE_93,RH__FE_92,RH__FE_91,RH__FE_90,RH__FE_89,RH__FE_88,RH__FE_87,RH__FE_86,RH__FE_85,RH__FE_84,RH__FE_83,RH__FE_82,RH__FE_81,RH__FE_80,RH__FE_79,RH__FE_78,RH__FE_77,RH__FE_76,RH__FE_75,RH__FE_74,RH__FE_73,RH__FE_72,RH__FE_71,RH__FE_70,RH__FE_69,RH__FE_68,RH__FE_67,RH__FE_66,RH__FE_65,RH__FE_64,RH__FE_63,RH__FE_62,RH__FE_61,RH__FE_60,RH__FE_59,RH__FE_58,RH__FE_57,RH__FE_56,RH__FE_55,RH__FE_54,RH__FE_53,RH__FE_52,RH__FE_51,RH__FE_50,RH__FE_49,RH__FE_48,RH__FE_47,RH__FE_46,RH__FE_45,RH__FE_44,RH__FE_43,RH__FE_42,RH__FE_41,RH__FE_40,RH__FE_39,RH__FE_38,RH__FE_37,RH__FE_36,RH__FE_35,RH__FE_34,RH__FE_33,RH__FE_32,RH__FE_31,RH__FE_30,RH__FE_29,RH__FE_28,RH__FE_27,RH__FE_26,RH__FE_25,RH__FE_24,RH__FE_23,RH__FE_22,RH__FE_21,RH__FE_20,RH__FE_19,RH__FE_18,RH__FE_17,RH__FE_16,RH__FE_15,RH__FE_14,RH__FE_13,RH__FE_12,RH__FE_11,RH__FE_10,RH__FE_9,RH__FE_8,RH__FE_7,RH__FE_6,RH__FE_5,RH__FE_4,RH__FE_3,RH__FE_2,RH__FE_1,)(action,__VA_ARGS__))

#endif //__RH_FOR_EACH_h__
